### ISSUE TITLE
No longer working for 1.7.10?

### ISSUE THREAD

**Issue by devryb** [rlf/uSkyBlock#506]
[01:26:21] [Server thread/ERROR]: Error occurred while enabling uSkyBlock v2.4.7 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.from(Ljava/lang/String;)Lguava10/com/google/common/cache/CacheBuilder;
	at us.talabrek.ultimateskyblock.challenge.ChallengeCompletionLogic.<init>(ChallengeCompletionLogic.java:35) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.<init>(ChallengeLogic.java:62) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:1090) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:205) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1448.152]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1448.152]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1448.152]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1448.152]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1448.152]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:158) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]

**Comment by dutchy1001** [comment]
plz give us the info from the command /usb version.

**Comment by rlf** [comment]
Yes, we started using Guava v18.0, which comes pre-packaged in Spigot 1.8.
In 1.7.10, they use Guava v10.0 - which is honestly just too old for us to maintain.

If you are willing - or have someone willing - to support and maintain a 1.7.10 branch - you are welcome to do so.

**Comment by devryb** [comment]
Thanks for the information.
Will get back to you on that, our dev is fairly busy at the moment on other projects.

**Comment by rlf** [comment]
Actually, it seems to only be the "string-constructor" we use that isn't supported in Guava 10.

See http://docs.guava-libraries.googlecode.com/git-history/v10.0.1/javadoc/com/google/common/cache/CacheBuilder.html

So perhaps we can (with relatively small effort), stay 1.7.10 compatible.

**Comment by rlf** [comment]
Just did some testing - the incompatibilities are quite severe.

An option would then be, to shade guava into the uSkyBlock jar - but we don't want to do that for v1.8 (it more than doubles the size of the jar).

**Comment by hunter688** [comment]
How I can shade guava into uSkyBlock.jar please? What version is the latest, which works with 1.7.10 and guava 10? Will be possible make some changes mentioned in previous comments? Many server still on the 1.7.10 (modded, cauldron). Please make something like backport to guava 10. Thanks a lot.

**Comment by rlf** [comment]
@hunter688 we do not intend to support 1.7.10 moving forward - I suggest you stay on the latest v1.7.10 compatible version of uSkyBlock, or find someone who wants to spent time maintaining 1.7.10.

I know you are not alone in wanting the 1.7.10 support, but we prefer to focus on the new features for 1.8, and soon to be 1.9.

**Comment by csorrows** [comment]
I agree with rlf, there is no reason to take a step back here. Forward progress is being made and should continue.

**Comment by dutchy1001** [comment]
What I don't understand is why the "modeded" community or Cauldron haven't made 1.8 server files. It's almost a year now 1.8 has been released and 1.9 is around the corner. Time for them to get their act together. Spigot done it so why not them??
Don't get me wrong I will support any version we release but that is not the point.

**Comment by rlf** [comment]
I think most of the modded community relies on the MCP (http://www.modcoderpack.com/website/releases) to make modded releases, and they were a long time getting over the shit-storm Wesley Wolfe caused - it seems though, that they now supports 1.8, so odds are Forge and other modded servers will update soon.

**Comment by dutchy1001** [comment]
let's hope, saves us a lot of tests and work

**Comment by rlf** [comment]
Forge is out with 1.8 support, but Cauldron (aka MCPC+) has totally abandoned Bukkit (due to Wesley Frakking may he live in medieval agony Wolfe), in favor of SpongePowered.

**Comment by hunter688** [comment]
Thanks for 2.4 branch and commit https://github.com/rlf/uSkyBlock/commit/bcafafe287ab9910afc3ff39aa2aad8be5de9a1f

it works in the 1.7.10, great work, thanks again!

**Comment by devryb** [comment]
hmm i had tried the 2.4 branch and got a similar issue with the guava which doesn't make sense to me, I'll look at it more tomorrow

[15:18:02] [Server thread/INFO]: [uSkyBlock] Enabling uSkyBlock v2.4.0-SNAPSHOT
[15:18:03] [Server thread/INFO]: No plugins\uSkyBlock\config.yml found, it will be created
[15:18:03] [Server thread/INFO]: [uSkyBlock] 0 schematics loaded.
[15:18:03] [Server thread/INFO]: No plugins\uSkyBlock\challenges.yml found, it will be created
[15:18:03] [Server thread/ERROR]: Error occurred while enabling uSkyBlock v2.4.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.from(Ljava/lang/String;)Lguava10/com/google/common/cache/CacheBuilder;
	at us.talabrek.ultimateskyblock.challenge.ChallengeCompletionLogic.<init>(ChallengeCompletionLogic.java:36) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.<init>(ChallengeLogic.java:62) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:1146) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:210) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1448.150]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1448.150]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1448.150]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1448.150]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1448.150]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:158) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]

**Comment by hunter688** [comment]
@devryb you must compile it with -PshadeGuava argument.
mvn -PshadeGuava package

**Comment by devryb** [comment]
Thanks, ya waiting for http://www.sk89q.com/ to be online so we can try again.
But if anyone has the compiled version they don't mind sending that works too.

**Comment by rlf** [comment]
It's available on the web-page http://rlf.github.io/uSkyBlock/

**Comment by devryb** [comment]
Awesome thanks
